// Auto-generated seed data parsed from school roster.
// Format: { name, rollNumber, grade, house }

export const SEED_STUDENTS = [
  // ── 5a (9 students) ──────────────────────────────────────────────────────────
  { grade: '5a', rollNumber: '202-26-1', name: 'Abdul Hadi',          house: 'Qarshi' },
  { grade: '5a', rollNumber: '424-25-1', name: 'Abdul Malik',         house: 'Qarshi' },
  { grade: '5a', rollNumber: '252-25-1', name: 'Ghayyur Ashal',       house: 'Qarshi' },
  { grade: '5a', rollNumber: '275-25-1', name: 'Ghayyur Murtajiz',    house: 'Qarshi' },
  { grade: '5a', rollNumber: '216-25-1', name: 'Haziq Hyder',         house: 'Qarshi' },
  { grade: '5a', rollNumber: '083-26-1', name: 'Mohid Bin Mugheera',  house: 'Qarshi' },
  { grade: '5a', rollNumber: '055-25-1', name: 'Muhammad Hashim',     house: 'Qarshi' },
  { grade: '5a', rollNumber: '086-25-1', name: 'Muhammad Musa',       house: 'Qarshi' },
  { grade: '5a', rollNumber: '042-25-2', name: 'Uzair Arslan',        house: 'Qarshi' },

  // ── 6a (22 students) ─────────────────────────────────────────────────────────
  { grade: '6a', rollNumber: '156-25-1', name: 'Abdul Rehman',                house: 'Qarshi' },
  { grade: '6a', rollNumber: '264-24-2', name: 'Abu Bakar',                   house: 'Qarshi' },
  { grade: '6a', rollNumber: '422-25-1', name: 'Ahad Noor',                   house: 'Qarshi' },
  { grade: '6a', rollNumber: '274-24-2', name: 'Ahmad',                       house: 'Qarshi' },
  { grade: '6a', rollNumber: '168-25-1', name: 'Ali Moosa',                   house: 'Qarshi' },
  { grade: '6a', rollNumber: '155-25-1', name: 'Ch. Ayan Ali',                house: 'Qarshi' },
  { grade: '6a', rollNumber: '037-25-1', name: 'Ghulam Musa Raza',            house: 'Qarshi' },
  { grade: '6a', rollNumber: '161-25-1', name: 'Hamza Cheema Mukhtar',        house: 'Qarshi' },
  { grade: '6a', rollNumber: '227-24-2', name: 'Hamza Ismail',                house: 'Qarshi' },
  { grade: '6a', rollNumber: '052-24-2', name: 'Mohammad',                    house: 'Qarshi' },
  { grade: '6a', rollNumber: '135-26-1', name: 'Muhammad Ismail',             house: 'Qarshi' },
  { grade: '6a', rollNumber: '272-25-1', name: 'Muhammad Rashid Sultan',      house: 'Qarshi' },
  { grade: '6a', rollNumber: '021-24-1', name: 'Muhammad Rizwan',             house: 'Mehran' },
  { grade: '6a', rollNumber: '381-25-1', name: 'Muhammad Saadoon Javed',      house: 'Qarshi' },
  { grade: '6a', rollNumber: '036-24-1', name: 'Muhammad Samar Abbas',        house: 'Qarshi' },
  { grade: '6a', rollNumber: '236-24-2', name: 'Muhammad Shayan',             house: 'Qarshi' },
  { grade: '6a', rollNumber: '192-25-1', name: 'Muhammad Waqas Khyzar',       house: 'Qarshi' },
  { grade: '6a', rollNumber: '013-26-1', name: 'Rana Muhammad Bilal',         house: 'Qarshi' },
  { grade: '6a', rollNumber: '259-25-1', name: 'Rayhan Ali',                  house: 'Qarshi' },
  { grade: '6a', rollNumber: '244-24-3', name: 'Rayyan Abbas',                house: 'Qarshi' },
  { grade: '6a', rollNumber: '397-24-1', name: 'Sahil',                       house: 'Qarshi' },
  { grade: '6a', rollNumber: '276-24-1', name: 'Usman Farooq Jathol',         house: 'Qarshi' },

  // ── 7a (19 students) ─────────────────────────────────────────────────────────
  { grade: '7a', rollNumber: '114-24-1', name: 'Abdul Wahab',               house: 'Qarshi'  },
  { grade: '7a', rollNumber: '061-24-1', name: 'Abdullah Umer Bhatti',      house: 'Qarshi'  },
  { grade: '7a', rollNumber: '185-25-1', name: 'Arsal Karim',               house: 'Qarshi'  },
  { grade: '7a', rollNumber: '228-23-1', name: 'Bilal Khan',                house: 'AJ'      },
  { grade: '7a', rollNumber: '088-23-1', name: 'Bin Yameen',                house: 'Qarshi'  },
  { grade: '7a', rollNumber: '098-25-1', name: 'Hassan Hyder',              house: 'Qarshi'  },
  { grade: '7a', rollNumber: '261-25-1', name: 'Mohammad Abdul Aayan',      house: 'Qarshi'  },
  { grade: '7a', rollNumber: '044-23-1', name: 'Muhammad Ali',              house: 'Qarshi'  },
  { grade: '7a', rollNumber: '053-24-1', name: 'Muhammad Anas',             house: 'Qarshi'  },
  { grade: '7a', rollNumber: '262-25-2', name: 'Muhammad Hassan Haider',    house: 'Qarshi'  },
  { grade: '7a', rollNumber: '111-25-1', name: 'Muhammad Inamullah',        house: 'Abaseen' },
  { grade: '7a', rollNumber: '330-25-1', name: 'Muhammad Muhid',            house: 'Qarshi'  },
  { grade: '7a', rollNumber: '304-25-1', name: 'Muhammad Osama Jan Butt',   house: 'Qarshi'  },
  { grade: '7a', rollNumber: '063-25-1', name: 'Muhammad Saad',             house: 'Qarshi'  },
  { grade: '7a', rollNumber: '296-24-1', name: 'Muhammad Sanwal Nawaz',     house: 'Qarshi'  },
  { grade: '7a', rollNumber: '434-25-1', name: 'Sahil Aziz',                house: 'Qarshi'  },
  { grade: '7a', rollNumber: '436-25-1', name: 'Shah Rukh Khan',            house: 'Qarshi'  },
  { grade: '7a', rollNumber: '197-24-1', name: 'Shahrazullah',              house: 'Qarshi'  },
  { grade: '7a', rollNumber: '106-24-2', name: 'Sohail Ahmad',              house: 'Qarshi'  },

  // ── 7b (19 students) ─────────────────────────────────────────────────────────
  { grade: '7b', rollNumber: '313-25-1', name: 'Abdul Majid',               house: 'Qarshi'  },
  { grade: '7b', rollNumber: '357-25-1', name: 'Buraq Malik',               house: 'Abaseen' },
  { grade: '7b', rollNumber: '082-23-2', name: 'Farhan Ahmad',              house: 'Abaseen' },
  { grade: '7b', rollNumber: '395-24-1', name: 'Fitras Hussain',            house: 'Qarshi'  },
  { grade: '7b', rollNumber: '255-24-1', name: 'Haider Ali',                house: 'Qarshi'  },
  { grade: '7b', rollNumber: '091-25-1', name: 'Hassan Akbar',              house: 'Qarshi'  },
  { grade: '7b', rollNumber: '402-24-1', name: 'Ibrahim Arif',              house: 'Abaseen' },
  { grade: '7b', rollNumber: '433-25-1', name: 'Iqbal Asad',                house: 'Qarshi'  },
  { grade: '7b', rollNumber: '432-25-1', name: 'Jaffer Muhammad Raza',      house: 'Qarshi'  },
  { grade: '7b', rollNumber: '077-24-1', name: 'Kamal Siddique',            house: 'Qarshi'  },
  { grade: '7b', rollNumber: '073-23-1', name: 'Mudassir Sher',             house: 'Qarshi'  },
  { grade: '7b', rollNumber: '016-25-1', name: 'Muhammad Abdullah',         house: 'AJ'      },
  { grade: '7b', rollNumber: '019-26-1', name: 'Muhammad Ali Khawaja',      house: 'Abaseen' },
  { grade: '7b', rollNumber: '416-25-1', name: 'Muhammad Bilal Anjum',      house: 'Qarshi'  },
  { grade: '7b', rollNumber: '186-25-1', name: 'Muhammad Ibraheem Mahmood', house: 'Qarshi'  },
  { grade: '7b', rollNumber: '212-24-1', name: 'Muhammad Soban Shakeel',    house: 'Saigol'  },
  { grade: '7b', rollNumber: '319-24-1', name: 'Musa Ali Tarar',            house: 'Abaseen' },
  { grade: '7b', rollNumber: '278-24-1', name: 'Solat Hussain',             house: 'Qarshi'  },
  { grade: '7b', rollNumber: '138-25-1', name: 'Yasir Yaseen',              house: 'Ghani'   },

  // ── 8a (24 students) ─────────────────────────────────────────────────────────
  { grade: '8a', rollNumber: '054-26-1', name: 'Abdullah Abrar Toor',       house: 'Ghani'   },
  { grade: '8a', rollNumber: '145-23-1', name: 'Ahmad Mansha',              house: 'Mehran'  },
  { grade: '8a', rollNumber: '043-25-1', name: 'Ahmad Subhan',              house: 'ZH'      },
  { grade: '8a', rollNumber: '152-22-1', name: 'Ahmed Usman',               house: 'Saigol'  },
  { grade: '8a', rollNumber: '400-24-1', name: 'Ammar Shahzad',             house: 'Abaseen' },
  { grade: '8a', rollNumber: '271-25-1', name: 'Faiz Mahmood',              house: 'ZH'      },
  { grade: '8a', rollNumber: '409-24-1', name: 'Haider Sher',               house: 'Abaseen' },
  { grade: '8a', rollNumber: '020-24-1', name: 'Muhammad Abdullah',         house: 'Saigol'  },
  { grade: '8a', rollNumber: '041-25-1', name: 'Muhammad Abdullah Saleem',  house: 'Saigol'  },
  { grade: '8a', rollNumber: '289-25-1', name: 'Muhammad Aief',             house: 'ZH'      },
  { grade: '8a', rollNumber: '421-24-1', name: 'Muhammad Anas Riaz',        house: 'ZH'      },
  { grade: '8a', rollNumber: '160-25-1', name: 'Muhammad Farhan Qamar',     house: 'Abaseen' },
  { grade: '8a', rollNumber: '245-24-1', name: 'Muhammad Ibrahim Khan',     house: 'Ghani'   },
  { grade: '8a', rollNumber: '118-25-1', name: 'Muhammad Saad',             house: 'Sanobar' },
  { grade: '8a', rollNumber: '379-23-1', name: 'Muhammad Subhan Zia Khan',  house: 'AJ'      },
  { grade: '8a', rollNumber: '256-25-1', name: 'Muhammad Yousaf',           house: 'Abaseen' },
  { grade: '8a', rollNumber: '332-23-1', name: 'Qalb-e-Abbas Shah',         house: 'Saigol'  },
  { grade: '8a', rollNumber: '163-26-1', name: 'Saad Basheer Toor',         house: 'Ghani'   },
  { grade: '8a', rollNumber: '147-26-1', name: 'Sardar Rohan Ahmad Khan',   house: 'ZH'      },
  { grade: '8a', rollNumber: '423-25-1', name: 'Shayane Ali Butt',          house: 'Mehran'  },
  { grade: '8a', rollNumber: '190-24-1', name: 'Sohail Ahmed',              house: 'AJ'      },
  { grade: '8a', rollNumber: '177-26-1', name: 'Subhan Ahmed',              house: 'Ghani'   },
  { grade: '8a', rollNumber: '239-25-1', name: 'Wasif Ahmad',               house: 'Mehran'  },
  { grade: '8a', rollNumber: '141-26-1', name: 'Zulqarnain Haider',         house: 'Sanobar' },

  // ── 8b (23 students) ─────────────────────────────────────────────────────────
  { grade: '8b', rollNumber: '383-23-1', name: 'Aleem Arif',                    house: 'Saigol'  },
  { grade: '8b', rollNumber: '431-25-1', name: 'Aliyan Ahmad',                  house: 'Abaseen' },
  { grade: '8b', rollNumber: '139-25-1', name: 'Ameer Mahvia',                  house: 'Ghani'   },
  { grade: '8b', rollNumber: '191-25-1', name: 'Azan Raheel Shami',             house: 'AJ'      },
  { grade: '8b', rollNumber: '426-25-1', name: 'Farman Ali',                    house: 'Abaseen' },
  { grade: '8b', rollNumber: '178-25-1', name: 'Hafiz Muhammad Salman Qasim',   house: 'ZH'      },
  { grade: '8b', rollNumber: '375-23-1', name: 'Hassan Jan',                    house: 'Abaseen' },
  { grade: '8b', rollNumber: '411-25-1', name: 'Ibrahim Noor Muhammad',         house: 'ZH'      },
  { grade: '8b', rollNumber: '194-25-1', name: 'Khizar Ahmad',                  house: 'ZH'      },
  { grade: '8b', rollNumber: '270-24-1', name: 'Malik Allah Yaar Khan',         house: 'Ghani'   },
  { grade: '8b', rollNumber: '171-26-1', name: 'Muhammad Abdullah',             house: 'Mehran'  },
  { grade: '8b', rollNumber: '150-23-1', name: 'Muhammad Ahsan',                house: 'Saigol'  },
  { grade: '8b', rollNumber: '356-23-1', name: 'Muhammad Arham',                house: 'AJ'      },
  { grade: '8b', rollNumber: '290-25-1', name: 'Muhammad Hammad',               house: 'Sanobar' },
  { grade: '8b', rollNumber: '121-24-1', name: 'Muhammad Hamza Warraich',       house: 'Saigol'  },
  { grade: '8b', rollNumber: '281-24-1', name: 'Muhammad Sikandar Khan',        house: 'Saigol'  },
  { grade: '8b', rollNumber: '074-23-1', name: 'Muhammad Umar',                 house: 'Saigol'  },
  { grade: '8b', rollNumber: '253-24-2', name: 'Muhammad Umar Farooq',          house: 'Saigol'  },
  { grade: '8b', rollNumber: '066-24-1', name: 'Muhammad Usman',                house: 'Sanobar' },
  { grade: '8b', rollNumber: '119-25-1', name: 'Safiullah',                     house: 'AJ'      },
  { grade: '8b', rollNumber: '398-24-1', name: 'Salim',                         house: 'Ghani'   },
  { grade: '8b', rollNumber: '014-26-1', name: 'Shawaiz Ahmed',                 house: 'Abaseen' },
  { grade: '8b', rollNumber: '016-26-1', name: 'Zain Ali',                      house: 'Mehran'  },

  // ── 8c (20 students) ─────────────────────────────────────────────────────────
  { grade: '8c', rollNumber: '210-26-1', name: 'Abdul Mateen',                   house: 'Mehran'  },
  { grade: '8c', rollNumber: '316-24-1', name: 'Abdullah Jibran',                house: 'Ghani'   },
  { grade: '8c', rollNumber: '092-25-1', name: 'Abdullah Yousaf',                house: 'Saigol'  },
  { grade: '8c', rollNumber: '361-23-1', name: 'Ali Abdullah',                   house: 'ZH'      },
  { grade: '8c', rollNumber: '193-25-1', name: 'Aqib Naseeb',                    house: 'Mehran'  },
  { grade: '8c', rollNumber: '068-26-1', name: 'Chaudhry Fazan Yaqoob',          house: 'Abaseen' },
  { grade: '8c', rollNumber: '213-24-1', name: 'Hammad Ahmed',                   house: 'Sanobar' },
  { grade: '8c', rollNumber: '057-25-2', name: 'Khaliem Shazad Qayyum',          house: 'Mehran'  },
  { grade: '8c', rollNumber: '127-25-1', name: 'Mohammad Azan Ali',              house: 'Abaseen' },
  { grade: '8c', rollNumber: '151-26-1', name: 'Mohammad Waleed Amir',           house: 'ZH'      },
  { grade: '8c', rollNumber: '306-25-1', name: 'Muhammad Arham Ranjha',          house: 'Mehran'  },
  { grade: '8c', rollNumber: '365-23-1', name: 'Muhammad Arsal',                 house: 'Ghani'   },
  { grade: '8c', rollNumber: '100-25-1', name: 'Muhammad Hussain Ali',           house: 'Saigol'  },
  { grade: '8c', rollNumber: '133-25-1', name: 'Muhammad Hussnain Qasim Butt',   house: 'Sanobar' },
  { grade: '8c', rollNumber: '231-23-1', name: 'Muhammad Riaz',                  house: 'AJ'      },
  { grade: '8c', rollNumber: '050-26-1', name: 'Muhammad Suleman',               house: 'Saigol'  },
  { grade: '8c', rollNumber: '023-25-1', name: 'Rai Muhammad Raza',              house: 'ZH'      },
  { grade: '8c', rollNumber: '051-25-1', name: 'Rayyan Yasir',                   house: 'Mehran'  },
  { grade: '8c', rollNumber: '028-23-1', name: 'Shanawar Sardar',                house: 'Abaseen' },
  { grade: '8c', rollNumber: '401-24-1', name: 'Talha Azam',                     house: 'Sanobar' },

  // ── 9a (17 students) ─────────────────────────────────────────────────────────
  { grade: '9a', rollNumber: '062-25-1', name: 'Abdul Moeez Ansar',           house: 'Saigol'  },
  { grade: '9a', rollNumber: '279-25-1', name: 'Aliyan Hameed',               house: 'Mehran'  },
  { grade: '9a', rollNumber: '435-25-1', name: 'Azam Khan',                   house: 'ZH'      },
  { grade: '9a', rollNumber: '076-25-1', name: 'Hamd Zaheer Minhas',          house: 'AJ'      },
  { grade: '9a', rollNumber: '326-24-1', name: 'Hassaan Bin Umer Tarar',      house: 'Abaseen' },
  { grade: '9a', rollNumber: '078-25-1', name: 'Mohammad Ali Tahir',          house: 'ZH'      },
  { grade: '9a', rollNumber: '291-23-1', name: 'Muhammad Abbas',              house: 'Ghani'   },
  { grade: '9a', rollNumber: '048-22-1', name: 'Muhammad Abdullah Chattha',   house: 'Abaseen' },
  { grade: '9a', rollNumber: '246-25-1', name: 'Muhammad Abdullah Chaudhry', house: 'Saigol'  },
  { grade: '9a', rollNumber: '087-25-1', name: 'Muhammad Abu Zar Naeem',      house: 'ZH'      },
  { grade: '9a', rollNumber: '002-23-1', name: 'Muhammad Awais Ali',          house: 'Abaseen' },
  { grade: '9a', rollNumber: '390-24-1', name: 'Muhammad Omer',               house: 'Ghani'   },
  { grade: '9a', rollNumber: '096-25-1', name: 'Muhammad Qamar',              house: 'Sanobar' },
  { grade: '9a', rollNumber: '056-25-1', name: 'Muhammad Rahim Khan',         house: 'Sanobar' },
  { grade: '9a', rollNumber: '204-24-2', name: 'Muhammad Usman Khan',         house: 'AJ'      },
  { grade: '9a', rollNumber: '403-24-1', name: 'Zarar Haider',                house: 'Abaseen' },
  { grade: '9a', rollNumber: '394-24-1', name: 'Zeeshan Rasool',              house: 'Mehran'  },

  // ── 9b (18 students) ─────────────────────────────────────────────────────────
  { grade: '9b', rollNumber: '282-25-1', name: 'Ahmed Bajwa',                 house: 'ZH'      },
  { grade: '9b', rollNumber: '200-25-1', name: 'Ahmed Kamal',                 house: 'Sanobar' },
  { grade: '9b', rollNumber: '124-26-1', name: 'Ali Aryan',                   house: 'Ghani'   },
  { grade: '9b', rollNumber: '034-22-1', name: 'Ali Imran',                   house: 'Saigol'  },
  { grade: '9b', rollNumber: '105-24-1', name: 'Awais Ali',                   house: 'Mehran'  },
  { grade: '9b', rollNumber: '238-25-1', name: 'Bilawal Zafar',               house: 'Mehran'  },
  { grade: '9b', rollNumber: '207-23-1', name: 'Malik Muhammad Ahmad Raza',   house: 'Ghani'   },
  { grade: '9b', rollNumber: '148-21-1', name: 'Muaaz Javaid',                house: 'Mehran'  },
  { grade: '9b', rollNumber: '084-26-1', name: 'Muhammad Abu Bakr',           house: 'ZH'      },
  { grade: '9b', rollNumber: '035-25-1', name: 'Muhammad Ahmed Sabri',        house: 'Saigol'  },
  { grade: '9b', rollNumber: '269-24-1', name: 'Muhammad Ayyan Masoom',       house: 'Abaseen' },
  { grade: '9b', rollNumber: '396-24-1', name: 'Muhammad Shozab Saqlain',     house: 'Ghani'   },
  { grade: '9b', rollNumber: '058-23-1', name: 'Muhammad Umer Shakeel',       house: 'Saigol'  },
  { grade: '9b', rollNumber: '360-25-1', name: 'Muhammad Unais',              house: 'AJ'      },
  { grade: '9b', rollNumber: '175-25-1', name: 'Saeed Muhammad Fiaz',         house: 'Abaseen' },
  { grade: '9b', rollNumber: '195-25-1', name: 'Umair Ahmed',                 house: 'Mehran'  },
  { grade: '9b', rollNumber: '179-25-1', name: 'Zarrar Ahmed Latif',          house: 'ZH'      },
  { grade: '9b', rollNumber: '079-25-1', name: 'Zayaan Ahmad Khan',           house: 'ZH'      },

  // ── 9c (19 students) ─────────────────────────────────────────────────────────
  { grade: '9c', rollNumber: '104-23-1', name: 'Abdul Ahad',                      house: 'Sanobar' },
  { grade: '9c', rollNumber: '095-25-1', name: 'Abdul Haadi',                     house: 'Sanobar' },
  { grade: '9c', rollNumber: '206-26-1', name: 'Ahmed Zeeshan Rafique',           house: 'Ghani'   },
  { grade: '9c', rollNumber: '283-24-1', name: 'Ahsan Asif',                      house: 'Mehran'  },
  { grade: '9c', rollNumber: '201-23-1', name: 'Ali Ahmad',                       house: 'AJ'      },
  { grade: '9c', rollNumber: '298-24-1', name: 'Ali Hassan',                      house: 'AJ'      },
  { grade: '9c', rollNumber: '208-24-2', name: 'Ali Hassan Amir',                 house: 'AJ'      },
  { grade: '9c', rollNumber: '070-24-1', name: 'Asfand Musa Chatha',              house: 'ZH'      },
  { grade: '9c', rollNumber: '428-25-1', name: 'Fahad Atta',                      house: 'Sanobar' },
  { grade: '9c', rollNumber: '072-23-1', name: 'Hafiz Zain ul Abideen Akhtar',    house: 'Mehran'  },
  { grade: '9c', rollNumber: '125-25-1', name: 'Hamza Nawaz',                     house: 'Mehran'  },
  { grade: '9c', rollNumber: '226-25-1', name: 'Muhammad Aun Raza',               house: 'Sanobar' },
  { grade: '9c', rollNumber: '427-25-1', name: 'Muhammad Bin Yousaf Malik',       house: 'Sanobar' },
  { grade: '9c', rollNumber: '188-24-1', name: 'Muhammad Sarim Warraich',         house: 'Mehran'  },
  { grade: '9c', rollNumber: '233-24-1', name: 'Muhammad Taha Shehzad',           house: 'ZH'      },
  { grade: '9c', rollNumber: '315-23-2', name: 'Muhammad Zameer',                 house: 'AJ'      },
  { grade: '9c', rollNumber: '406-24-1', name: 'Rana Wajahat',                    house: 'AJ'      },
  { grade: '9c', rollNumber: '355-23-2', name: 'Rayan Zaheer',                    house: 'Saigol'  },
  { grade: '9c', rollNumber: '001-21-1', name: 'Syed Muhammad Sakhi Hussain',     house: 'Abaseen' },

  // ── 9d (22 students) ─────────────────────────────────────────────────────────
  { grade: '9d', rollNumber: '122-25-1', name: 'Abdul Samee',              house: 'Sanobar' },
  { grade: '9d', rollNumber: '187-25-1', name: 'Ayaan Ali Askari',         house: 'Ghani'   },
  { grade: '9d', rollNumber: '180-23-1', name: 'Farid Ahmed',              house: 'Saigol'  },
  { grade: '9d', rollNumber: '288-24-1', name: 'Furqan Ali Nayyar',        house: 'Saigol'  },
  { grade: '9d', rollNumber: '209-24-1', name: 'Haider Ali',               house: 'Ghani'   },
  { grade: '9d', rollNumber: '223-21-1', name: 'Khuram Bashir',            house: 'ZH'      },
  { grade: '9d', rollNumber: '312-24-1', name: 'Mohammad Abdulhaddi',      house: 'Mehran'  },
  { grade: '9d', rollNumber: '046-23-1', name: 'Moin ud Din Hassan',       house: 'AJ'      },
  { grade: '9d', rollNumber: '169-23-1', name: 'Muhammad Asadullah',       house: 'Abaseen' },
  { grade: '9d', rollNumber: '224-21-2', name: 'Muhammad Faris Naqi',      house: 'Abaseen' },
  { grade: '9d', rollNumber: '030-24-1', name: 'Muhammad Furqan',          house: 'Abaseen' },
  { grade: '9d', rollNumber: '027-23-1', name: 'Muhammad Hassaan Yasir',   house: 'Ghani'   },
  { grade: '9d', rollNumber: '172-25-1', name: 'Muhammad Ibrahim',         house: 'Abaseen' },
  { grade: '9d', rollNumber: '199-24-1', name: 'Muhammad Ibrahim',         house: 'Ghani'   },
  { grade: '9d', rollNumber: '065-24-1', name: 'Muhammad Ismael',          house: 'Ghani'   },
  { grade: '9d', rollNumber: '029-22-1', name: 'Muhammad Mahad',           house: 'Ghani'   },
  { grade: '9d', rollNumber: '338-23-1', name: 'Muhammad Mubeen Shah',     house: 'AJ'      },
  { grade: '9d', rollNumber: '120-25-1', name: 'Muhammad Talha Waseem',    house: 'Sanobar' },
  { grade: '9d', rollNumber: '336-25-1', name: 'Muhammad Umer Iqbal',      house: 'Saigol'  },
  { grade: '9d', rollNumber: '164-25-1', name: 'Muhammad Uzair',           house: 'Saigol'  },
  { grade: '9d', rollNumber: '093-25-1', name: 'Roman Sheikh',             house: 'Mehran'  },
  { grade: '9d', rollNumber: '162-25-1', name: 'Shahmeer Ahmad Awan',      house: 'ZH'      },

  // ── 10a (13 students) ────────────────────────────────────────────────────────
  { grade: '10a', rollNumber: '366-23-1', name: 'Ahmed Ali Gondal',           house: 'Saigol'  },
  { grade: '10a', rollNumber: '080-25-1', name: 'Ali Jabran Rana',            house: 'Ghani'   },
  { grade: '10a', rollNumber: '225-23-2', name: 'Ali Murtaza',                house: 'Sanobar' },
  { grade: '10a', rollNumber: '005-20-1', name: 'Arman Shahid',               house: 'ZH'      },
  { grade: '10a', rollNumber: '170-24-3', name: 'Emaad Ahmad',                house: 'Mehran'  },
  { grade: '10a', rollNumber: '337-23-1', name: 'Husyan Shah',                house: 'Abaseen' },
  { grade: '10a', rollNumber: '367-23-1', name: 'Jawad Ullah Sahi',           house: 'Sanobar' },
  { grade: '10a', rollNumber: '173-22-1', name: 'Muhammad Azan Tahir',        house: 'Ghani'   },
  { grade: '10a', rollNumber: '015-24-1', name: 'Muhammad Badar Farid',       house: 'Sanobar' },
  { grade: '10a', rollNumber: '318-24-1', name: 'Muhammad Shoaib',            house: 'Abaseen' },
  { grade: '10a', rollNumber: '372-23-1', name: 'Muneeb Muhammad Aslam Kausar', house: 'Sanobar' },
  { grade: '10a', rollNumber: '257-24-1', name: 'Sikander Ali Goraya',        house: 'Sanobar' },
  { grade: '10a', rollNumber: '391-24-1', name: 'Syed Muhammad Baqir',        house: 'Sanobar' },

  // ── 10b (22 students) ────────────────────────────────────────────────────────
  { grade: '10b', rollNumber: '131-25-1', name: 'Abdullah Amjad Butt',           house: 'ZH'      },
  { grade: '10b', rollNumber: '010-25-1', name: 'Abdullah Bin Umar',             house: 'ZH'      },
  { grade: '10b', rollNumber: '123-23-1', name: 'Ahmad Murad',                   house: 'Mehran'  },
  { grade: '10b', rollNumber: '081-25-1', name: 'Ghalib Sultan Al Mehmood',      house: 'Ghani'   },
  { grade: '10b', rollNumber: '112-24-1', name: 'Ghulam Mustafa Khan',           house: 'Mehran'  },
  { grade: '10b', rollNumber: '222-24-1', name: 'Hamza Irfan',                   house: 'Sanobar' },
  { grade: '10b', rollNumber: '327-23-1', name: 'Hamza Tahir',                   house: 'AJ'      },
  { grade: '10b', rollNumber: '346-22-1', name: 'Khuda Dad',                     house: 'Ghani'   },
  { grade: '10b', rollNumber: '412-24-1', name: 'Mabeer Bilal',                  house: 'Mehran'  },
  { grade: '10b', rollNumber: '407-24-1', name: 'Mohammad Shayan Adil',          house: 'Saigol'  },
  { grade: '10b', rollNumber: '265-23-1', name: 'Muhammad Abbas',                house: 'ZH'      },
  { grade: '10b', rollNumber: '311-24-1', name: 'Muhammad Faiz Naveed Ghuman',   house: 'AJ'      },
  { grade: '10b', rollNumber: '393-24-1', name: 'Muhammad Shayan',               house: 'Saigol'  },
  { grade: '10b', rollNumber: '425-25-1', name: 'Muhammad Shoaib Aftab',         house: 'ZH'      },
  { grade: '10b', rollNumber: '149-23-1', name: 'Muhammad Subhan',               house: 'ZH'      },
  { grade: '10b', rollNumber: '309-22-1', name: 'Muhammad Taha',                 house: 'Ghani'   },
  { grade: '10b', rollNumber: '219-23-1', name: 'Mureed Ali',                    house: 'Sanobar' },
  { grade: '10b', rollNumber: '144-25-1', name: 'Saim Zafar',                    house: 'ZH'      },
  { grade: '10b', rollNumber: '115-23-2', name: 'Shahzaib',                      house: 'Abaseen' },
  { grade: '10b', rollNumber: '287-24-1', name: 'Subhan Khan',                   house: 'ZH'      },
  { grade: '10b', rollNumber: '322-22-1', name: 'Talha Baig',                    house: 'Sanobar' },
  { grade: '10b', rollNumber: '215-24-2', name: 'Umar Nadeem',                   house: 'Sanobar' },

  // ── 10c (16 students) ────────────────────────────────────────────────────────
  { grade: '10c', rollNumber: '299-24-1', name: 'Ahmad Ghazanfar',              house: 'AJ'      },
  { grade: '10c', rollNumber: '140-19-1', name: 'Ahmad Javed',                  house: 'AJ'      },
  { grade: '10c', rollNumber: '218-23-1', name: 'Anas Qamar',                   house: 'Saigol'  },
  { grade: '10c', rollNumber: '017-21-1', name: 'Artaza Haider',                house: 'Abaseen' },
  { grade: '10c', rollNumber: '277-24-1', name: 'Azan Ali Nayyar',              house: 'Saigol'  },
  { grade: '10c', rollNumber: '369-24-1', name: 'Hassan Rizwan Iqbal',          house: 'ZH'      },
  { grade: '10c', rollNumber: '240-20-1', name: 'Irfan',                        house: 'Sanobar' },
  { grade: '10c', rollNumber: '022-25-1', name: 'Ismail Fahad',                 house: 'Saigol'  },
  { grade: '10c', rollNumber: '075-24-3', name: 'Jawad Akhtar',                 house: 'ZH'      },
  { grade: '10c', rollNumber: '363-23-1', name: 'Muhammad Ali Hassan',          house: 'ZH'      },
  { grade: '10c', rollNumber: '384-23-1', name: 'Muhammad Arshman Shahzad',     house: 'Saigol'  },
  { grade: '10c', rollNumber: '166-23-1', name: 'Muhammad Asad Khan',           house: 'Abaseen' },
  { grade: '10c', rollNumber: '417-24-1', name: 'Muhammad Raheel Malik',        house: 'Abaseen' },
  { grade: '10c', rollNumber: '418-24-1', name: 'Muhammad Shehriyar Malik',     house: 'Abaseen' },
  { grade: '10c', rollNumber: '331-25-1', name: 'Musa Ghazali',                 house: 'Mehran'  },
  { grade: '10c', rollNumber: '260-20-1', name: 'Sha Mureed',                   house: 'Sanobar' },

  // ── 10d (21 students) ────────────────────────────────────────────────────────
  { grade: '10d', rollNumber: '134-24-1', name: 'Abdul Ahad',                   house: 'Ghani'   },
  { grade: '10d', rollNumber: '157-25-1', name: 'Abdul Hadi Ghuman',            house: 'Ghani'   },
  { grade: '10d', rollNumber: '364-23-1', name: 'Ahmed Hussain Shahzad',        house: 'ZH'      },
  { grade: '10d', rollNumber: '273-21-1', name: 'Ameer Hamza',                  house: 'AJ'      },
  { grade: '10d', rollNumber: '300-24-2', name: 'Aryan Faisal',                 house: 'Mehran'  },
  { grade: '10d', rollNumber: '174-24-2', name: 'Asad Ali',                     house: 'Mehran'  },
  { grade: '10d', rollNumber: '399-24-1', name: 'Dil Nawaz Aslam',              house: 'ZH'      },
  { grade: '10d', rollNumber: '254-23-2', name: 'Dilawar Azeem',                house: 'Sanobar' },
  { grade: '10d', rollNumber: '038-22-1', name: 'Haseeb Yousaf',                house: 'Mehran'  },
  { grade: '10d', rollNumber: '374-23-1', name: 'Hussain Jan',                  house: 'Abaseen' },
  { grade: '10d', rollNumber: '085-24-1', name: 'Muhammad',                     house: 'Mehran'  },
  { grade: '10d', rollNumber: '103-24-2', name: 'Muhammad Abdullah',            house: 'Sanobar' },
  { grade: '10d', rollNumber: '362-23-1', name: 'Muhammad Ali Safdar',          house: 'Saigol'  },
  { grade: '10d', rollNumber: '012-23-1', name: 'Muhammad Sami Ullah',          house: 'Abaseen' },
  { grade: '10d', rollNumber: '211-19-2', name: 'Muhammad Sami Ullah',          house: 'AJ'      },
  { grade: '10d', rollNumber: '101-24-1', name: 'Muhammad Sarim Afzal',         house: 'Saigol'  },
  { grade: '10d', rollNumber: '414-24-1', name: 'Muhammad Tashfeen Awan',       house: 'Ghani'   },
  { grade: '10d', rollNumber: '242-24-1', name: 'Muhammad Usman Ghani',         house: 'Ghani'   },
  { grade: '10d', rollNumber: '268-24-2', name: 'Muhammad Waqas',               house: 'AJ'      },
  { grade: '10d', rollNumber: '205-22-1', name: 'Shehriyar Sami',               house: 'Abaseen' },
  { grade: '10d', rollNumber: '241-24-1', name: 'Sheikh Muhammad Sufiyan',      house: 'Ghani'   },
];
